[package]
name = "ATcmd_search_10376_3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.5.0", features = ["desktop"] }
dioxus-desktop = "0.5.0"
roxmltree = "0.20.0"

